// Cloudinary asset URLs
// This file is auto-generated by the migration script
// Run: npm run migrate:static-assets (from server directory) to update

export const cloudinaryAssets = {
  videoUrl: "https://res.cloudinary.com/dnow3xhka/video/upload/v1763552958/ben-gigi/static-assets/home-video.mp4",
  osmoticsLogoUrl: "https://res.cloudinary.com/dnow3xhka/image/upload/v1763553114/ben-gigi/static-assets/osmotics-logo.png",
  benGigiLogoUrl: "https://res.cloudinary.com/dnow3xhka/image/upload/v1763553115/ben-gigi/static-assets/ben-gigi-logo.svg",
};

// Fallback URLs (will be replaced after migration)
export const fallbackAssets = {
  videoUrl: "https://www.mosmatic.com/videos/Home_EN.mp4",
  osmoticsLogoUrl: "/src/assets/osmotics logo.png",
  benGigiLogoUrl: "/waterLoaderSvg.svg",
};

// Helper function to get asset URL with fallback
export const getAssetUrl = (
  assetType: "video" | "osmoticsLogo" | "benGigiLogo"
): string => {
  switch (assetType) {
    case "video":
      return (
        cloudinaryAssets.videoUrl || fallbackAssets.videoUrl
      );
    case "osmoticsLogo":
      return (
        cloudinaryAssets.osmoticsLogoUrl ||
        fallbackAssets.osmoticsLogoUrl
      );
    case "benGigiLogo":
      return (
        cloudinaryAssets.benGigiLogoUrl ||
        fallbackAssets.benGigiLogoUrl
      );
    default:
      return "";
  }
};
